In [2]:
import sqlite3
import pandas as pd

conexion = sqlite3.connect("../bases_datos/ventas.db")

In [3]:
consulta_clientes = "SELECT COUNT(*) AS TotalClientes FROM Clientes;"
pd.read_sql_query(consulta_clientes, conexion)

   TotalClientes
0             12

In [4]:
consulta_productos = """
SELECT
    COUNT(*) AS TotalProductos,
    AVG(PrecioVenta) AS PrecioMedio,
    MIN(PrecioVenta) AS PrecioMinimo,
    MAX(PrecioVenta) AS PrecioMaximo,
    SUM(Stock) AS StockTotal
FROM Productos;
"""
pd.read_sql_query(consulta_productos, conexion)

   TotalProductos  PrecioMedio  PrecioMinimo  PrecioMaximo  StockTotal
0              15   142.613333           3.9         799.0        3815

In [5]:
consulta_ventas = """
SELECT
    COUNT(DISTINCT Ventas.IdVenta) AS TotalVentasRegistradas,
    SUM((Cantidad * PrecioUnitario) - ((Cantidad * PrecioUnitario * (Descuento / 100)))) AS FacturacionTotal
FROM LineasVenta
INNER JOIN Ventas ON LineasVenta.IdVenta = Ventas.IdVenta;
"""
pd.read_sql_query(consulta_ventas, conexion)

   TotalVentasRegistradas  FacturacionTotal
0                      24          17786.99

In [6]:
consulta_ventas = """
SELECT
    COUNT(DISTINCT Ventas.IdVenta) AS TotalVentasRegistradas,
    SUM((Cantidad * PrecioUnitario) - ((Cantidad * PrecioUnitario * (Descuento / 100)))) AS FacturacionTotal
FROM LineasVenta
INNER JOIN Ventas ON LineasVenta.IdVenta = Ventas.IdVenta;
"""
pd.read_sql_query(consulta_ventas, conexion)

   TotalVentasRegistradas  FacturacionTotal
0                      24          17786.99

In [7]:
conexion.close()

#INFORME RESUMIDO DEL ESTADO DEL NEGOCIO

#1. Indicadores de Clientes
* **Total de clientes registrados:** 12

#2. Indicadores de Productos y Almacén
* **Total de productos en catálogo:** 15
* **Precio medio de los productos:** 142.613333	
* **Rango de precios:** Desde 3.9	hasta 799.0	
* **Stock total disponible en almacén:** 3815


#3. Indicadores de Ventas y Rendimiento
* **Total de ventas registradas:** 24
* **Facturación total real:** 17.786,99